import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import "./globals.css";
import Footer from "@/components/Footer";
import { cn } from "@/lib/utils";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faLandmark } from "@fortawesome/free-solid-svg-icons";
import Nav from "@/components/Nav";
import AuthProvider from "./context/AuthProvider";
const logo1 = <FontAwesomeIcon icon={faLandmark} className="w-6" />;

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "bg-background min-h-screen font-sans antialised",
          fontSans.variable
        )}
      >
        <AuthProvider>
          <Nav logo={logo1}></Nav>
          {children}
          <Footer></Footer>
        </AuthProvider>
      </body>
    </html>
  );
}
